/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.IMainController;
import controller.MainControllerImpl;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import model.Marcos;
import model.Proceso;

/**
 *
 * @author SAMSUNG
 */
public class MainJFrame extends javax.swing.JFrame implements IMainView{
    
    private final IMainController mainController;
    private final int NO_PAGINAS = 6;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        this.mainController = new MainControllerImpl(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnListaCompleta = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTMarcos = new javax.swing.JTextField();
        btnAgregarProceso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEjecucion = new javax.swing.JButton();
        btnEspera = new javax.swing.JButton();
        btnFinalizado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtCero = new javax.swing.JTextField();
        txtUno = new javax.swing.JTextField();
        txtDos = new javax.swing.JTextField();
        txtTres = new javax.swing.JTextField();
        txtCuatro = new javax.swing.JTextField();
        txtCinco = new javax.swing.JTextField();
        txtSeis = new javax.swing.JTextField();
        txtSiete = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PAGINACION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Marco de página");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        btnListaCompleta.setBackground(new java.awt.Color(255, 153, 0));
        btnListaCompleta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListaCompleta.setForeground(new java.awt.Color(255, 255, 255));
        btnListaCompleta.setText("Lista de procesos");
        btnListaCompleta.setName("btnLista"); // NOI18N
        btnListaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaCompletaActionPerformed(evt);
            }
        });

        txtNombre.setName("txtNombre"); // NOI18N

        jLabel11.setText("Nombre");

        jLabel12.setText("Numero de marcos");

        txtTMarcos.setName("txtTMarcos"); // NOI18N

        btnAgregarProceso.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarProceso.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProceso.setText("Agregar proceso");
        btnAgregarProceso.setName("btnAgregar"); // NOI18N
        btnAgregarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProcesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(61, 61, 61)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTMarcos)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnAgregarProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTMarcos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarProceso)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 329));

        btnEjecucion.setBackground(new java.awt.Color(0, 204, 0));
        btnEjecucion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEjecucion.setForeground(new java.awt.Color(255, 255, 255));
        btnEjecucion.setText("Procesos en ejecución");
        btnEjecucion.setName("btnEjecucion"); // NOI18N
        btnEjecucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecucionActionPerformed(evt);
            }
        });

        btnEspera.setBackground(new java.awt.Color(255, 255, 0));
        btnEspera.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEspera.setText("Procesos en espera");
        btnEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsperaActionPerformed(evt);
            }
        });

        btnFinalizado.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFinalizado.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizado.setText("Procesos terminados");
        btnFinalizado.setName("btnTerminados"); // NOI18N
        btnFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEjecucion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnFinalizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 300));

        txtCero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCero.setName("txtCero"); // NOI18N

        txtUno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUno.setName("txtUno"); // NOI18N

        txtDos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDos.setName("txtDos"); // NOI18N

        txtTres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTres.setName("txtTres"); // NOI18N

        txtCuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCuatro.setName("txtCuatro"); // NOI18N

        txtCinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCinco.setName("txtCinco"); // NOI18N

        txtSeis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeis.setName("txtSeis"); // NOI18N

        txtSiete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSiete.setName("txtSiete"); // NOI18N

        jLabel2.setText("0");

        jLabel3.setText("1");

        jLabel4.setText("2");

        jLabel5.setText("3");

        jLabel6.setText("4");

        jLabel7.setText("5");

        jLabel8.setText("6");

        jLabel9.setText("7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUno, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtCero)
                    .addComponent(txtDos)
                    .addComponent(txtTres)
                    .addComponent(txtCuatro)
                    .addComponent(txtCinco)
                    .addComponent(txtSeis)
                    .addComponent(txtSiete))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProcesoActionPerformed
        // TODO add your handling code here:
        
        if(txtNombre.getText().isEmpty() || txtTMarcos.getText().isEmpty()){
            
            onError("Complete los campos");
            
        }else{
            
            String nombre = txtNombre.getText();
            String marcos = txtTMarcos.getText();
            int nMarcos = 0;
            
            try{
                nMarcos = Integer.parseInt(marcos);
                
                if(nMarcos <= NO_PAGINAS){
                    Proceso proceso = new Proceso();
                    proceso.setNombre(nombre);
                    proceso.setMarcoPagina(nMarcos);

                    mainController.agregarProcesos(proceso);

                    txtNombre.setText("");
                    txtTMarcos.setText("");
                }else{
                    onError("El numero máximo de marcos es 6");
                }
                
            }
            catch(NumberFormatException e){
                onError("Ingrese un numero de marcos válido");
            }
           
        }
        
    }//GEN-LAST:event_btnAgregarProcesoActionPerformed

    private void btnListaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaCompletaActionPerformed
        // TODO add your handling code here:
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        
        ListaJDialog listaTask = new ListaJDialog(this, true);
        
        final int x = (screenSize.width - listaTask.getWidth()) / 2;
        final int y = (screenSize.height - listaTask.getHeight()) / 2;
        listaTask.setLocation(x,y);
        listaTask.setVisible(true);
    }//GEN-LAST:event_btnListaCompletaActionPerformed

    private void btnEjecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecucionActionPerformed
        // TODO add your handling code here:
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        
        EjecucionJDialog ejecucionTask = new EjecucionJDialog(this, true);
        
        final int x = (screenSize.width - ejecucionTask.getWidth()) / 2;
        final int y = (screenSize.height - ejecucionTask.getHeight()) / 2;
        ejecucionTask.setLocation(x,y);
        ejecucionTask.setVisible(true);
        
        ejecucionTask.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                mainController.refrescar();
                super.windowClosed(e); //To change body of generated methods, choose Tools | Templates.
                
            }
            
        });
    }//GEN-LAST:event_btnEjecucionActionPerformed

    private void btnEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsperaActionPerformed
        // TODO add your handling code here:
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        
        EsperaJDialog esperaTask = new EsperaJDialog(this, true);
        
        final int x = (screenSize.width - esperaTask.getWidth()) / 2;
        final int y = (screenSize.height - esperaTask.getHeight()) / 2;
        esperaTask.setLocation(x,y);
        esperaTask.setVisible(true);
    }//GEN-LAST:event_btnEsperaActionPerformed

    private void btnFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizadoActionPerformed
        // TODO add your handling code here:
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        
        FinalizadoJDialog finalizadoTask = new FinalizadoJDialog(this, true);
        
        final int x = (screenSize.width - finalizadoTask.getWidth()) / 2;
        final int y = (screenSize.height - finalizadoTask.getHeight()) / 2;
        finalizadoTask.setLocation(x,y);
        finalizadoTask.setVisible(true);
                
    }//GEN-LAST:event_btnFinalizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProceso;
    private javax.swing.JButton btnEjecucion;
    private javax.swing.JButton btnEspera;
    private javax.swing.JButton btnFinalizado;
    private javax.swing.JButton btnListaCompleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCero;
    private javax.swing.JTextField txtCinco;
    private javax.swing.JTextField txtCuatro;
    private javax.swing.JTextField txtDos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSeis;
    private javax.swing.JTextField txtSiete;
    private javax.swing.JTextField txtTMarcos;
    private javax.swing.JTextField txtTres;
    private javax.swing.JTextField txtUno;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onError(String msg) {
        JOptionPane.showMessageDialog(null,msg);
    }

    @Override
    public void onRefreshView(List<Marcos> lista) {
        for(int i = 0; i < lista.size(); i++){
            if(lista.get(i).getEstado() == 1){
                //System.out.println(lista.get(i).getEstado());
                procesarTarea(lista.get(i));
            }else{
                //System.out.println(lista.get(i).getEstado());
                limpiarTarea(lista.get(i));
            }
        }
    }

    private void procesarTarea(Marcos marco) {
        
        switch(marco.getNombre()){
            case "txtCero":
                txtCero.setText(marco.getNombreProceso());
                txtCero.setBackground(Color.red);
                txtCero.setForeground(Color.WHITE);
                txtCero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;
            case "txtUno":
                txtUno.setText(marco.getNombreProceso());
                txtUno.setBackground(Color.red);
                txtUno.setForeground(Color.WHITE);
                txtUno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;
            case "txtDos":
                txtDos.setText(marco.getNombreProceso());
                txtDos.setBackground(Color.red);
                txtDos.setForeground(Color.WHITE);
                txtDos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;
            case "txtTres":
                txtTres.setText(marco.getNombreProceso());
                txtTres.setBackground(Color.red);
                txtTres.setForeground(Color.WHITE);
                txtTres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;
            case "txtCuatro":
                txtCuatro.setText(marco.getNombreProceso());
                txtCuatro.setBackground(Color.red);
                txtCuatro.setForeground(Color.WHITE);
                txtCuatro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;
            case "txtCinco":
                txtCinco.setText(marco.getNombreProceso());
                txtCinco.setBackground(Color.red);
                txtCinco.setForeground(Color.WHITE);
                txtCinco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;
            case "txtSeis":
                txtSeis.setText(marco.getNombreProceso());
                txtSeis.setBackground(Color.red);
                txtSeis.setForeground(Color.WHITE);
                txtSeis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;
            case "txtSiete":
                txtSiete.setText(marco.getNombreProceso());
                txtSiete.setBackground(Color.red);
                txtSiete.setForeground(Color.WHITE);
                txtSiete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                break;    
                
        }
    }

    private void limpiarTarea(Marcos marco) {
        switch(marco.getNombre()){
            case "txtCero":
                txtCero.setText("");
                txtCero.setBackground(Color.WHITE);
                txtCero.setForeground(Color.BLACK);
                break;
            case "txtUno":
                txtUno.setText("");
                txtUno.setBackground(Color.WHITE);
                txtUno.setForeground(Color.BLACK);
                break;
            case "txtDos":
                txtDos.setText("");
                txtDos.setBackground(Color.WHITE);
                txtDos.setForeground(Color.BLACK);
                break;
            case "txtTres":
                txtTres.setText("");
                txtTres.setBackground(Color.WHITE);
                txtTres.setForeground(Color.BLACK);
                break;
            case "txtCuatro":
                txtCuatro.setText("");
                txtCuatro.setBackground(Color.WHITE);
                txtCuatro.setForeground(Color.BLACK);
                break;
            case "txtCinco":
                txtCinco.setText("");
                txtCinco.setBackground(Color.WHITE);
                txtCinco.setForeground(Color.BLACK);
                break;
            case "txtSeis":
                txtSeis.setText("");
                txtSeis.setBackground(Color.WHITE);
                txtSeis.setForeground(Color.BLACK);
                break;
            case "txtSiete":
                txtSiete.setText("");
                txtSiete.setBackground(Color.WHITE);
                txtSiete.setForeground(Color.BLACK);
                break;      
                
        }
    }
}
